[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_add = '''
'''
hook_source = '''
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'sources': [
    \     {'name': 'file_rec', 'params': {}},
    \     {'name': 'rg', 'params': {}},
    \   ],
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_fzf'],
    \     },
    \   },
    \   'sourceParams': {
    \     'rg': {
    \       'args': ['--column', '--no-heading', '--color', 'never', '--json'],
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   },
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:true,
    \     }
    \   },
    \   'filterParams': {
    \     'matcher_fzf': {
    \       'highlightMatched': 'Search',
    \     }
    \   },
    \ })
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>
nnoremap <buffer> <C-c> <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''
ddu-ff-filter = '''
inoremap <buffer> <CR> <Esc><Cmd>close<CR>
inoremap <buffer> <C-c> <Esc><Cmd>close<CR><Cmd>call ddu#ui#ff#do_action('quit')<CR>
nnoremap <buffer> <CR> <Cmd>close<CR>
nnoremap <buffer><silent> q <Cmd>close<CR>
nnoremap <buffer> <C-c> <Cmd>close<CR><Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'
hook_add = '''
    command! DduFileRec call <SID>ddu_file_rec()
    function! s:ddu_file_rec() abort
      let l:project_root = FindGitRoot()
      call ddu#start({
            \   'sources': [{
            \     'name': 'file_rec',
            \     'options': {'path': l:project_root},
            \   }],
            \ })
    endfunction
'''

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'
hook_add = '''
    command! DduRgLive call <SID>ddu_rg_live()
    function! s:ddu_rg_live() abort
      let l:project_root = FindGitRoot()
      call ddu#start({
            \   'volatile': v:true,
            \   'sources': [{
            \     'name': 'rg',
            \     'params': {'path': l:project_root},
            \     'options': {'matchers': []},
            \   }],
            \   'uiParams': {'ff': {
            \     'ignoreEmpty': v:false,
            \     'autoResize': v:false,
            \   }},
            \ })
    endfunction
'''

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'
hook_add = '''
     nnoremap [ddu] <Nop>
     nmap <Leader>u [ddu]
     nnoremap <silent> [ddu]p     <Cmd>DduFileRec<CR>
     nnoremap <silent> [ddu]g     <Cmd>DduRgLive<CR>
'''
