[[plugins]]
repo = 'jonathanfilip/vim-lucius'
hook_add = '''
    set background=dark
    augroup MyColorScheme
        au!
        au VimEnter * nested colorscheme lucius
    augroup END
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'LucHermitte/lh-vim-lib'

[[plugins]]
repo = 'LucHermitte/alternate-lite'
depends = ['lh-vim-lib']

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo='vim-denops/denops.vim'

[[plugins]]
repo='neovim/nvim-lspconfig'

[[plugins]]
repo='williamboman/nvim-lsp-installer'
hook_source='''
lua <<EOF
local lsp_installer = require("nvim-lsp-installer")

-- Register a handler that will be called for all installed servers.
-- Alternatively, you may also register handlers on specific server instances instead (see example below).
lsp_installer.on_server_ready(function(server)
    local opts = {}

    -- (optional) Customize the options passed to the server
    -- if server.name == "tsserver" then
    --     opts.root_dir = function() ... end
    -- end

    if server.name == "jedi_language_server" then
        opts.diagnostics = {enable = false}
        opts.completion = {ignorePatterns = {"^_{1,3}$|^_[^_].*$|^__.*(?<!__)$"} }
    end

    -- This setup() function is exactly the same as lspconfig's setup function.
    -- Refer to https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
    server:setup(opts)
end)
EOF
'''
